name: Fly Deploy
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    name: studybuddy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run:  pip install -r requirements.txt
      - run: flyctl deploy -a studybuddy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
